
export const mockPatients = [
  {
    id: 'PAT001',
    name: 'María González',
    age: 45,
    gender: 'F',
    bloodType: 'O+',
    allergies: ['Penicilina', 'Polen'],
    lastVisit: '2025-11-15',
    diagnosis: 'Hipertensión controlada',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },
  {
    id: 'PAT002',
    name: 'Carlos Ramírez',
    age: 62,
    gender: 'M',
    bloodType: 'A+',
    allergies: ['Ninguna'],
    lastVisit: '2025-11-10',
    diagnosis: 'Diabetes tipo 2',
    status: 'critical',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },
  {
    id: 'PAT003',
    name: 'Ana Martínez',
    age: 34,
    gender: 'F',
    bloodType: 'B-',
    allergies: ['Mariscos'],
    lastVisit: '2025-11-18',
    diagnosis: 'Control prenatal',
    status: 'stable',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  },
  {
    id: 'PAT004',
    name: 'Luis Fernández',
    age: 55,
    gender: 'M',
    bloodType: 'AB+',
    allergies: ['AINES'],
    lastVisit: '2025-10-25',
    diagnosis: 'Revisión de rutina',
    status: 'active',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  }
];

export const mockVitalSigns = {
  labels: ['08:00', '12:00', '16:00', '20:00', '00:00', '04:00'],
  datasets: [
    {
      label: 'Ritmo Cardíaco',
      data: [72, 75, 78, 73, 70, 68],
      borderColor: 'rgba(59, 130, 246, 1)',
      backgroundColor: 'rgba(59, 130, 246, 0.2)',
      yAxisID: 'y',
    },
    {
      label: 'SpO2',
      data: [98, 97, 98, 99, 98, 97],
      borderColor: 'rgba(16, 185, 129, 1)',
      backgroundColor: 'rgba(16, 185, 129, 0.2)',
      yAxisID: 'y1',
    },
    {
      label: 'Temperatura',
      data: [36.5, 36.7, 36.6, 36.5, 36.4, 36.3],
      borderColor: 'rgba(239, 68, 68, 1)',
      backgroundColor: 'rgba(239, 68, 68, 0.2)',
      yAxisID: 'y2',
    }
  ],
};

export const mockCases = [
  {
    id: 'CASE001',
    title: 'Demanda Laboral - TechCorp vs. Empleado',
    client: 'TechCorp S.A.',
    caseType: 'Laboral',
    status: 'active',
    priority: 'high',
    nextHearing: '2025-12-15',
    assignedTo: 'Lic. Roberto Sánchez',
    progress: 65,
  },
  {
    id: 'CASE002',
    title: 'Divorcio Contencioso - Familia Pérez',
    client: 'Laura Pérez',
    caseType: 'Familiar',
    status: 'review',
    priority: 'medium',
    nextHearing: '2025-12-20',
    assignedTo: 'Lic. María Torres',
    progress: 40,
  },
  {
    id: 'CASE003',
    title: 'Contrato Mercantil - Fusión Empresarial',
    client: 'Grupo Industrial MX',
    caseType: 'Mercantil',
    status: 'pending',
    priority: 'urgent',
    nextHearing: '2026-01-05',
    assignedTo: 'Lic. Jorge Mendoza',
    progress: 85,
  },
];

export const mockPolicies = [
  {
    id: 'POL001',
    policyNumber: 'AUTO-2025-001',
    client: 'Juan Hernández',
    type: 'Automóvil',
    coverage: 'Amplia',
    premium: 12500,
    status: 'active',
    expiryDate: '2026-11-30',
    vehicle: 'Toyota Corolla 2024',
  },
  {
    id: 'POL002',
    policyNumber: 'VIDA-2025-002',
    client: 'Patricia López',
    type: 'Vida',
    coverage: 'Total',
    premium: 8900,
    status: 'active',
    expiryDate: '2026-06-30',
    sumInsured: 2000000,
  },
  {
    id: 'POL003',
    policyNumber: 'HOME-2025-003',
    client: 'Roberto García',
    type: 'Hogar',
    coverage: 'Completa',
    premium: 15200,
    status: 'expired',
    expiryDate: '2025-10-15',
    property: 'Casa Residencial',
  },
];

export const mockClients = [
  {
    id: 'CLI001',
    name: 'Distribuidora del Norte S.A.',
    rfc: 'DNO901234ABC',
    regime: 'General de Ley',
    status: 'active',
    monthlyBilling: 450000,
    pendingReturns: ['Octubre 2025'],
    contact: 'Lic. Fernando Ruiz',
  },
  {
    id: 'CLI002',
    name: 'Servicios Profesionales MX',
    rfc: 'SPM890123DEF',
    regime: 'Personas Físicas',
    status: 'review',
    monthlyBilling: 180000,
    pendingReturns: ['Septiembre 2025', 'Octubre 2025'],
    contact: 'C.P. Sandra Morales',
  },
  {
    id: 'CLI003',
    name: 'Comercializadora Global',
    rfc: 'CGO789012GHI',
    regime: 'General de Ley',
    status: 'active',
    monthlyBilling: 780000,
    pendingReturns: [],
    contact: 'Lic. Miguel Ángel Cruz',
  },
];

export const mockHospitalBeds = [
  {
    id: 'BED001',
    number: '101-A',
    floor: 1,
    wing: 'Norte',
    status: 'occupied',
    patient: 'José Ramírez',
    diagnosis: 'Post-operatorio',
    assignedNurse: 'Enf. Laura Soto',
    admissionDate: '2025-11-20',
  },
  {
    id: 'BED002',
    number: '102-B',
    floor: 1,
    wing: 'Norte',
    status: 'available',
    patient: null,
    diagnosis: null,
    assignedNurse: null,
    admissionDate: null,
  },
  {
    id: 'BED003',
    number: '201-A',
    floor: 2,
    wing: 'Sur',
    status: 'maintenance',
    patient: null,
    diagnosis: null,
    assignedNurse: null,
    admissionDate: null,
  },
  {
    id: 'BED004',
    number: '103-C',
    floor: 1,
    wing: 'Norte',
    status: 'occupied',
    patient: 'Carmen Flores',
    diagnosis: 'Observación',
    assignedNurse: 'Enf. Pedro Vega',
    admissionDate: '2025-11-22',
  },
];

export const mockItineraries = [
  {
    id: 'ITIN001',
    patient: 'Michael Johnson',
    origin: 'New York, USA',
    destination: 'Cancún, México',
    procedure: 'Cirugía Bariátrica',
    arrivalDate: '2026-02-10',
    departureDate: '2026-02-20',
    status: 'confirmed',
    hotel: 'Grand Cancún Resort',
    doctor: 'Dr. Alejandro Ruiz',
    totalCost: 85000,
    progress: 80,
    coordinates: { lat: 21.1619, lng: -86.8515 }
  },
  {
    id: 'ITIN002',
    patient: 'Sarah Williams',
    origin: 'Toronto, Canada',
    destination: 'Guadalajara, México',
    procedure: 'Implantes Dentales',
    arrivalDate: '2026-02-15',
    departureDate: '2026-02-22',
    status: 'pending',
    hotel: 'Hotel Demetria',
    doctor: 'Dra. Patricia Gómez',
    totalCost: 42000,
    progress: 30,
    coordinates: { lat: 20.6736, lng: -103.344 }
  },
  {
    id: 'ITIN003',
    patient: 'David Brown',
    origin: 'London, UK',
    destination: 'Ciudad de México',
    procedure: 'Cirugía Estética',
    arrivalDate: '2026-03-01',
    departureDate: '2026-03-10',
    status: 'quote',
    hotel: 'Four Seasons CDMX',
    doctor: 'Dr. Carlos Mendoza',
    totalCost: 125000,
    progress: 10,
    coordinates: { lat: 19.4326, lng: -99.1332 }
  },
];

export const mockTasks = [
    { id: 1, title: "Preparar declaración mensual para Cliente A", priority: "High", status: 'todo', dueDate: "2025-11-30", assignee: "Tú", assigneeInitials: "TÚ", project: "Contable" },
    { id: 2, title: "Seguimiento de siniestro de Póliza 123", priority: "Medium", status: 'in-progress', dueDate: "2025-12-02", assignee: "Ana M.", assigneeInitials: "AM", project: "Seguros" },
    { id: 3, title: "Revisar expediente clínico de Paciente X", priority: "High", status: 'in-progress', dueDate: "2025-11-28", assignee: "Dr. L.", assigneeInitials: "DL", project: "Médico" },
    { id: 4, title: "Redactar borrador de contrato para Fusión Y", priority: "High", status: 'done', dueDate: "2025-12-05", assignee: "Tú", assigneeInitials: "TÚ", project: "Legal" },
    { id: 5, title: "Llamada de seguimiento con Paciente Z", priority: "Low", status: 'done', dueDate: "2025-12-01", assignee: "Tú", assigneeInitials: "TÚ", project: "Médico" },
    { id: 6, title: "Confirmar reserva de hotel para Itinerario 002", priority: "Medium", status: 'todo', dueDate: "2025-11-29", assignee: "Carlos R.", assigneeInitials: "CR", project: "Turismo Médico" },
    { id: 7, title: "Auditoría de cama 201-A", priority: "Low", status: 'todo', dueDate: "2025-12-03", assignee: "Admin", assigneeInitials: "AD", project: "Hospital" },
];
